wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708937970.267404
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.18
      5: 0.16.3
      8:
      - 1
      - 5
      10:
      - 3
      13: linux-x86_64
