wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708938873.865762
    t:
      1:
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.18
      5: 0.16.3
      8:
      - 1
      - 5
      10:
      - 3
      13: linux-x86_64
    framework: huggingface
learning_rate:
  desc: null
  value: 5.0e-05
epochs:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 64
